### PR TITLE
Show alert if the browser blocks popups

### PR DESCRIPTION
**Pull request by vrde**
Chrome blocks pop–ups by default. If a tab is blocked, the script is throwing an error. Also, only one tab is used instead of 5.

image

This PR detects if the browser blocked some pop–ups and shows a nice message to the user, inviting them to enable the pop–ups to make more noise.

### CODE REVIEW

**Comment by slifty** [comment]
Great catch -- it looks like this commit will not re-open tabs that have been closed (originally it would open a new tab if the tab hadn't been opened OR if .closed was true)

I believe this can be solved by using a base level elseif to catch the "blocked" case instead of a nested set of ifs.

**Comment by vrde** [comment]
OK! I'll try to update the PR later today :smiley_cat:.

**Comment by vrde** [comment]
@slifty I changed the logic a bit, it should work as expected now.

**Comment by slifty** [comment]
the main thing holding me back from merging this is that it uses alerts, which I would like to avoid from a usability perspective -- I do like the idea.

One side issue is that I think for non-technical users they don't really care if it is only opening one tab, and a message COULD simply scare them away from using the tool.  On the other hand, technical users are more likely to notice.  That being said, if we make the message friendly (and ideally not an "alert") I'm sure the wording could be non-intimidating.

**Comment by vrde** [comment]
Agree. I've removed the `alert` and moved the message in the HTML page. I've also added an image that should help the users finding the tiny icon. We might survive even if it's not "retina ready".

image

**Comment by slifty** [comment]
(sorry for the delay in merging this @vrde)

**Comment by vrde** [comment]
No problem, thanks for merging!

**Pull request merged**
